/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.OpStackDescriptor');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.ZoneOpDescriptor');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.OpStackDescriptor = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.OpStackDescriptor.repeatedFields_, null);
};
goog.inherits(proto.OpStackDescriptor, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.OpStackDescriptor.displayName = 'proto.OpStackDescriptor';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.OpStackDescriptor.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.OpStackDescriptor.prototype.toObject = function(opt_includeInstance) {
  return proto.OpStackDescriptor.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.OpStackDescriptor} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.OpStackDescriptor.toObject = function(includeInstance, msg) {
  var f, obj = {
    dimensionX: jspb.Message.getFieldWithDefault(msg, 1, 0),
    dimensionY: jspb.Message.getFieldWithDefault(msg, 2, 0),
    focusIndex: jspb.Message.getFieldWithDefault(msg, 3, 0),
    opsList: jspb.Message.toObjectList(msg.getOpsList(),
    proto.ZoneOpDescriptor.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.OpStackDescriptor}
 */
proto.OpStackDescriptor.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.OpStackDescriptor;
  return proto.OpStackDescriptor.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.OpStackDescriptor} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.OpStackDescriptor}
 */
proto.OpStackDescriptor.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setDimensionX(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setDimensionY(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setFocusIndex(value);
      break;
    case 4:
      var value = new proto.ZoneOpDescriptor;
      reader.readMessage(value,proto.ZoneOpDescriptor.deserializeBinaryFromReader);
      msg.addOps(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.OpStackDescriptor.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.OpStackDescriptor.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.OpStackDescriptor} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.OpStackDescriptor.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDimensionX();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getDimensionY();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getFocusIndex();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getOpsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.ZoneOpDescriptor.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint32 dimension_x = 1;
 * @return {number}
 */
proto.OpStackDescriptor.prototype.getDimensionX = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.OpStackDescriptor.prototype.setDimensionX = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 dimension_y = 2;
 * @return {number}
 */
proto.OpStackDescriptor.prototype.getDimensionY = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.OpStackDescriptor.prototype.setDimensionY = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 focus_index = 3;
 * @return {number}
 */
proto.OpStackDescriptor.prototype.getFocusIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.OpStackDescriptor.prototype.setFocusIndex = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * repeated ZoneOpDescriptor ops = 4;
 * @return {!Array.<!proto.ZoneOpDescriptor>}
 */
proto.OpStackDescriptor.prototype.getOpsList = function() {
  return /** @type{!Array.<!proto.ZoneOpDescriptor>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ZoneOpDescriptor, 4));
};


/** @param {!Array.<!proto.ZoneOpDescriptor>} value */
proto.OpStackDescriptor.prototype.setOpsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.ZoneOpDescriptor=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ZoneOpDescriptor}
 */
proto.OpStackDescriptor.prototype.addOps = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.ZoneOpDescriptor, opt_index);
};


proto.OpStackDescriptor.prototype.clearOpsList = function() {
  this.setOpsList([]);
};


